# Generated by Django 4.0.3 on 2022-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('parent_name', models.TextField(blank=True, default='Parent Name not specified', null=True)),
                ('adhar', models.TextField(default='1', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='SubjectName', max_length=120, unique=True)),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('student_marks', models.IntegerField()),
            ],
            options={
                'unique_together': {('subject_id', 'student_id')},
            },
        ),
    ]
